### PR TITLE
Integrate with Travis

### PR DESCRIPTION
**Pull request by dsavenko**
Hi,

This PR adds integration with travis-ci.org. You can check the Travis build for the fork to see how it looks: https://travis-ci.org/dsavenko/ck . 

I added one very simple test ('test_safe_float'), because without any tests Travis build is next to useless. This test and the 'tests/' folder should be refactored in subsequent PRs about testing. 

After merging, you need to log in travis-ci.org and enable travis for the CK repository.

P.S. The button is README doesn't look as intended yet, because I changed the URL to the future URL of the upstream travis build, which doesn't yet exist. It should start working as soon as you enable Travis for the project.

### CODE REVIEW

**Comment by gfursin** [comment]
Looks good to me! Thanks!

**Comment by gfursin** [comment]
Hi Dmitry,
This looks good to me - thanks a lot!
I enabled ctuning/ck at travis-ci.org .
At the moment, the status of build is unknown.

What should I do to run the test? Or it will be done automatically
next time I commit something?

Thanks again,
Grigori

**Comment by gfursin** [comment]
Tried to push dummy change and Travis works fine - I see the 'passing' status in CK readme! Cool! Thanks!

**Comment by dsavenko** [comment]
Yes, it builds automatically on each commit. Also, it should do separate builds for pull requests (the 'Pull Requests' tab in Travis) — but I never tried. Also, there is a button 'Restart build' (round icon to the right6 below 'More options'), which allows to manually restart the build (build number is not incremented).

**Comment by gfursin** [comment]
Cool! Thanks! Very handy!

**Pull request merged**
