### PR TITLE
Tests runner and some tests for the kernel

### PR DESCRIPTION
**Pull request by dsavenko**
Hi,

This PRs introduces CK's own test runner (based on the standard Python's unittest module) and some tests for the kernel.

### User perspective

You can run tests with this command: `ck run test`. 

In this format, the command runs every test in every repository it found (including the default one). 

To specify which tests to run, you may use one or more of the following arguments:

1. `--repo_uoa` - if given, only tests for this repo are run. Example: `ck run test --repo_uoa=default` to run only tests for the default repo.

2. `--test_module_uoa` - if given, only tests for modules with this UOA are run. Example: `ck run test --repo_uoa=default --test_module_uoa=kernel` to run only tests for the kernel module in the default repo (the kernel itself).

3. `--test_file_pattern` - pattern for test file names to run (using shell style pattern matching). If not given, the assumed pattern is `test*.py`. Example: `ck run test --repo_uoa=default --test_module_uoa=kernel --test_file_pattern=test_original_tests.py` to run only the original tests for the kernel.

### Module/tests developer perspective

Tests for a module must reside in the `test/` directory in the module's CK entry. It's highly recommended that the files are named `test_SOMETHING.py' (replace _SOMETHING_ with something meaningful), as this is the default filename pattern. 

Tests are Python modules. The `ck`, `work` and `cfg` variables are injected by CK (just like they are for the modules). 

Tests Python modules must contain classes extending from `unittest.TestCase`. The actual testing methods are method of these classes called `test_*`. More information on standard tools for writing tests can be found here: https://docs.python.org/2/library/unittest.html

One can look at the kernel's tests for some examples: `ck/repo/module/kernel/test/test_kernel.py` and `ck/repo/module/kernel/test/test_original_tests.py`.

### Python target version changes

Python target versions are limited to Python 2.7 and Python 3.3+ (i.e. removed support for Python 2.6 and Python 3.2). This is necessary for using the `unittest` module's test discovery feature. Also, Python maintainers themselves recommend to not support version below 2.7 and 3.3 if possible, at least for bilingual programs (which CK is): https://wiki.python.org/moin/PortingToPy3k/BilingualQuickRef

### Kernel code changes

1. Fixed a bug in `ck.system_with_timeout(i)`, because of which the method returned incorrect return code in case of no timeout is given.

2. Removed `ck.test()`, as it seems to do nothing. One may use `ck version` to test CK installation.

3. Fixed some comments and documentation.

### Changes to the CK test module

1. The `test` action replaced with the `run` action. 

2. Three methods are provided in the test module: `run` (exposed as the action), `run_data_tests` and `run_module_tests`. The latter two are not exposed as actions, but can be if we find it useful.

### Changes to the kernel tests

Old (outdated) tests from the top `tests/` directory have been removed. Instead of them, there are a single `test.py` file there intended to be used with various automatic runners as an entry point for running unit tests and measuring coverage. This is how the tests can be run with the help of this file:

    python -m tests.test

(should be executed from the root `ck/` directory). This is essentially an equivalent of calling `ck run test` from the command line.

Some of the old tests are migrated to `ck/repo/module/kernel/test/test_original_tests.py`.

A bunch of new tests is written: `ck/repo/module/kernel/test/test_kernel.py`. This is not enough to cover the kernel, so more tests need to be added.

Travis setup changed to run the new tests.

## What should be done in subsequent PRs

1. Measure code coverage

2. Write more tests to cover the kernel better.

Please, share your thoughts.

### CODE REVIEW

**Comment by gfursin** [comment]
I didn't yet have time to look at the whole code, though a bit surprised to see directory "tests" in "repo/kernel/default", since it's an entry, not a module. The module is in ''repo/module/kernel''. I will need to dig further. 

In the mean time, I am rewriting full CK documentation and added a section "Testing" here:
https://github.com/ctuning/ck/wiki/Development#Testing
Do you mind to update it too, please?

Also, note that I added info about Python source code indentation. We should try to follow it at least for CK mainline since other people may be soon contributing we agreed to keep such indentation for now. 

Thanks a lot!!!

**Comment by dsavenko** [comment]
Moved the tests to `repo/module/kernel`. Sorry, missed this nuance.

**Comment by dsavenko** [comment]
> In the mean time, I am rewriting full CK documentation and added a section "Testing" here:
https://github.com/ctuning/ck/wiki/Development#Testing
> Do you mind to update it too, please?

Looks like I don't have write access to update that page. I guess, you can just copy/paste the first two sections ('User perspective' and 'Module/tests developer perspective') there...

**Comment by dsavenko** [comment]
Fixed indents.

**Comment by gfursin** [comment]
I accepted this commit. Thanks a lot!

**Pull request merged**
