### PR TITLE
Measure code coverage by tests

### PR DESCRIPTION
**Pull request by dsavenko**
Hi,

This PR enables code coverage measurement by tests. It uses the [Coveralls](http://coveralls.io/) service, which is free for open source projects. 

After merging, you need to log in [Coveralls](http://coveralls.io/) with the cTuning github account. It asks you to select payment plan — **you can skip this step**. Just move mouse to the left (where the menu is) and choose 'Add repo'. 

A list of your github repos appear. Select 'on' for CK. That's it!

You may need to build the repo again in travis. After that you can navigate to https://coveralls.io/github/ctuning/ck and check the coverage as well as detailed reports on which lines are covered.

The PR also adds the 'coverage' badge to README (next to the 'build' badge).

**Warning! This PR depends on the 'tests' [PR](https://github.com/ctuning/ck/pull/54) and should not be merged before that one.**

### CODE REVIEW

**Comment by gfursin** [comment]
The branch shows that there are some conflicts - maybe it happened since I did some merges in between. Do you mind to check what have happened, please? Then I will try to merge it!

**Comment by dsavenko** [comment]
Sure, I'll fix the conflicts and let you know, once it's done.

**Comment by dsavenko** [comment]
Fixed

**Comment by gfursin** [comment]
I have merged these changes and they seems to be working fine! Thanks a lot!!!

**Pull request merged**
